# Generated by Django 6.1 on 2026-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent / Guardian'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('STAFF', 'Staff')], default='SUPER_ADMIN', max_length=30),
        ),
    ]
