# Generated by Django 6.1 on 2026-09-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent / Guardian'), ('ACCOUNTANT', 'Finance Officer / Bursar'), ('ADMISSION_OFFICER', 'Admission Officer'), ('LIBRARIAN', 'Librarian'), ('EXAM_OFFICER', 'Exam / Assessment Officer'), ('COUNSELOR', 'Guidance Counselor'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('TRANSPORT_MANAGER', 'Transport Manager')], default='STUDENT', max_length=30),
        ),
    ]
