# Generated by Django 6.1 on 2026-09-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject'),
        ('students', '0003_remove_studentresult_unique_student_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_tracks', to='academics.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='students.academictrack'),
        ),
        migrations.AddConstraint(
            model_name='academictrack',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_academic_track_code'),
        ),
    ]
