# Generated by Django 6.1 on 2026-09-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_academictrack_studentenrollment_academic_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='parents/profile_images/'),
        ),
    ]
