# Generated by Django 6.1 on 2026-09-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
        ('students', '0005_parentguardian_profile_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academictrack',
            name='unique_school_academic_track_code',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_track',
        ),
        migrations.DeleteModel(
            name='AcademicTrack',
        ),
    ]
