# Generated by Django 6.1 on 2026-09-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
        ('students', '0006_remove_academictrack_unique_school_academic_track_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSubjectSelectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('max_optional_subjects', models.PositiveIntegerField(default=1)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject_selection_settings', to='academics.academicsession')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject_selection_settings', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject_selection_settings', to='academics.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject_selection_settings', to='academics.term')),
            ],
            options={
                'ordering': ['-academic_session', 'term', 'class_level'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_session', 'term', 'class_level'), name='unique_optional_subject_selection_setting')],
            },
        ),
    ]
