# Generated by Django 6.1 on 2026-09-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
        ('students', '0007_optionalsubjectselectionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_students', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('PROMOTED', 'Promoted'), ('GRADUATED', 'Graduated'), ('REPEATED', 'Repeated'), ('WITHDRAWN', 'Withdrawn')], default='PROMOTED', max_length=20)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from_class', to='academics.classlevel')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from', to='academics.academicsession')),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from_term', to='academics.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to_class', to='academics.classlevel')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to', to='academics.academicsession')),
                ('to_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to_term', to='academics.term')),
            ],
            options={
                'ordering': ['-promotion_date', '-id'],
            },
        ),
    ]
