# Generated by Django 6.1 on 2026-10-03 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
