# Generated by Django 6.1 on 2026-08-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('examination_type', models.CharField(choices=[('FIRST_CA', 'First Continuous Assessment'), ('SECOND_CA', 'Second Continuous Assessment'), ('MID_TERM', 'Mid-Term Examination'), ('MOCK', 'Mock Examination'), ('TERMINAL', 'Terminal Examination'), ('PROMOTION', 'Promotion Examination'), ('ENTRANCE', 'Entrance Examination')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.academicsession')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.term')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='examinations.examination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['examination_date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('examination', 'subject'), name='unique_examination_subject')],
            },
        ),
    ]
