# Generated by Django 6.1 on 2026-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='application_source',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('WALK_IN', 'Walk-in')], default='ONLINE', max_length=20),
        ),
    ]
