# Generated by Django 6.1 on 2026-09-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_applicant_application_source'),
        ('students', '0008_student_graduation_session_student_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='admitted_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student'),
        ),
    ]
