# Generated by Django 6.1 on 2026-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_applicant_admitted_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='local_government',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/profile_images/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
