# Generated by Django 6.1 on 2026-09-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
        ('admissions', '0004_applicant_admission_date_applicant_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='academics.term'),
        ),
    ]
