# Generated by Django 6.1 on 2026-09-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject'),
        ('students', '0004_academictrack_studentenrollment_academic_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='students.academictrack'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_level', 'subject', 'track'), name='unique_class_subject_track'),
        ),
    ]
