# Generated by Django 6.1 on 2026-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classsubject_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='education_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'JSS'), ('SS', 'Senior Secondary')], default='PRIMARY', max_length=10),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(help_text='Example: Primary 1, JSS 1, SS 1', max_length=100),
        ),
    ]
