# Generated by Django 6.1 on 2026-09-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classlevel_education_level_alter_classlevel_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classlevel',
            name='unique_school_class_code',
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level__in', ['PRIMARY', 'JSS'])), fields=('school', 'code'), name='unique_school_non_ss_class_code'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level', 'SS')), fields=('school', 'code', 'department'), name='unique_school_ss_class_department'),
        ),
    ]
