# Generated by Django 6.1 on 2026-09-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_classlevel_unique_school_class_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_school_subject_code',
        ),
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'JSS'), ('SS', 'Senior Secondary')], default='PRIMARY', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level__in', ['PRIMARY', 'JSS'])), fields=('school', 'code'), name='unique_school_non_ss_subject_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level', 'SS')), fields=('school', 'code', 'department'), name='unique_school_ss_subject_department'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credit_units',
        ),
    ]
