# Generated by Django 6.1 on 2026-09-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_subject_unique_school_subject_code_and_more'),
        ('students', '0005_parentguardian_profile_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classsubject',
            name='unique_class_subject_track',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='assignment_type',
            field=models.CharField(choices=[('GENERAL_COMPULSORY', 'General Compulsory'), ('DEPARTMENT_COMPULSORY', 'Department Compulsory'), ('OPTIONAL', 'Optional')], default='GENERAL_COMPULSORY', max_length=30),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Legacy field. Assignment type now determines whether the subject is compulsory or optional.'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='students.academictrack'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_level', 'subject', 'track', 'assignment_type'), name='unique_class_subject_assignment'),
        ),
    ]
