# Generated by Django 6.1 on 2026-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_classsubject_unique_class_subject_track_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classsubject',
            name='unique_class_subject_assignment',
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_level', 'subject', 'assignment_type'), name='unique_class_subject_assignment'),
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='track',
        ),
    ]
