# Generated by Django 6.1 on 2026-09-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='is_graduating_class',
            field=models.BooleanField(default=False, help_text='Marks this class as a final graduating class. Graduation can only be processed for students currently enrolled in a graduating class.'),
        ),
    ]
