# Generated by Django 6.1 on 2026-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payment_options_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='fee_categories',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='finance.studentinvoice'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All Fee Categories'), ('FEE_CATEGORIES', 'Selected Fee Categories'), ('INVOICES', 'Specific Invoices')], default='ALL', max_length=20),
        ),
    ]
