# Generated by Django 6.1 on 2026-09-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classsubject_unique_class_subject_assignment_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_school_opened', models.PositiveIntegerField(default=0, help_text='Number of times the school opened during this term.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='academics.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='academics.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='academics.term')),
            ],
            options={
                'ordering': ['-academic_session', 'term'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_session', 'term'), name='unique_school_attendance_setting')],
            },
        ),
    ]
