# Generated by Django 6.1 on 2026-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_classlevel_is_graduating_class'),
        ('attendance', '0002_schoolattendancesetting'),
        ('students', '0008_student_graduation_session_student_graduation_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_student_subject_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('student', 'date'), name='unique_student_general_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('student', 'subject', 'date'), name='unique_student_subject_attendance'),
        ),
    ]
