# Generated by Django 6.1 on 2026-09-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0008_student_graduation_session_student_graduation_year_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='targeted_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_type',
            field=models.CharField(choices=[('WHOLE_CLASS', 'Whole Class'), ('SELECTED_STUDENTS', 'Selected Students')], default='WHOLE_CLASS', max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='teachers.teacher'),
        ),
    ]
